name = "prompt-enhancer-worker"
main = "src/index.ts"
compatibility_date = "2024-07-06"

[durable_objects]
bindings = [
  { name = "RATE_LIMITER", class_name = "RateLimiter" },
  { name = "USAGE_AGGREGATOR", class_name = "UsageAggregator" },
  { name = "TOKEN_GATE", class_name = "TokenGate" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RateLimiter"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["UsageAggregator"]

[[migrations]]
tag = "v3"
new_sqlite_classes = ["TokenGate"]

[vars]
TURNSTILE_SITE_KEY = "0x4AAAAAABuJscKiniqQx6Re"
APP_HTTP_REFERER = "https://prompt-enhancer-worker.prompt-enhance-api.workers.dev"
ALLOWED_ORIGINS = "chrome-extension://jcnkcglepjnmblgdeeloojnbiaopammh"
ALLOWED_HOSTS = "claude.ai,chat.openai.com,chatgpt.com,gemini.google.com,grok.com,perplexity.ai"
MIN_ENHANCE_INTERVAL_MS = "3000"
RATE_LIMIT_BYPASS_SUBS = ""

APP_TITLE = "Enhance Prompt"
RATE_LIMIT_PER_DAY = "100"
MAX_PROMPT_CHARS = "4000"
REQUEST_TIMEOUT_MS = "15000"
DEFAULT_MODEL = "deepseek/deepseek-chat-v3.1:free"
DEFAULT_MAX_TOKENS = "500"
DEFAULT_TEMPERATURE = "0.7"
TOKEN_IP_LIMIT_PER_MIN = "5"
TOKEN_IP_BACKOFF_INITIAL_SEC = "60"
TOKEN_IP_BACKOFF_MAX_SEC = "900"