name = "enhance-prompt-api"
main = "src/index.ts"
compatibility_date = "2024-07-06"

 kv_namespaces = [
  { binding = "REQUEST_COUNT", id = "841b23c76c1749ebac24aad0e661fab4", preview_id = "841b23c76c1749ebac24aad0e661fab4" }
]


[vars]
APP_HTTP_REFERER = "https://enhance-prompt-api.prompt-enhance-api.workers.dev"
ALLOWED_ORIGINS = "chrome-extension://kbehgalhehmelfbaanamllcikeefangp"

APP_TITLE = "Enhance Prompt"
RATE_LIMIT_PER_DAY = "100"
MAX_PROMPT_CHARS = "4000"
REQUEST_TIMEOUT_MS = "15000"
DEFAULT_MODEL = "google/gemini-2.0-flash-exp:free"
DEFAULT_MAX_TOKENS = "500"
DEFAULT_TEMPERATURE = "0.7"